before_script:
  - apt-get update
  - apt-get install python3-dev python3-pip
  - pip3 install --upgrade pip setuptools
  - pip install flask gunicorn requests flask_wtf
  - export FLASK_APP=Flask.py
run_app:
  script:
    - flask run --host=0.0.0.0
